### ISSUE TITLE
Issue with Jedi after install vim-condo

### ISSUE THREAD

**Issue by kiennt23** [cjrh/vim-conda#27]
Hi, I have this issue after install vim-conda. It seems like it is not compatible with jedi-vim?

`Error detected while processing function jedi#init_python[4]..<SNR>41_init_python[27]..jedi#setup_python_imports:
line   25:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/Users/kiennguyen/.vim/bundle/jedi-vim/pythonx/jedi_vim_debug.py", line 5, in <module>
    from jedi_vim import PythonToVimStr
  File "/Users/kiennguyen/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 112, in <module>
    import jedi
  File "/Users/kiennguyen/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py", line 41, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, \
  File "/Users/kiennguyen/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 21, in <module>
    from jedi import debug
  File "/Users/kiennguyen/.vim/bundle/jedi-vim/pythonx/jedi/jedi/debug.py", line 23, in <module>
    from colorama import Fore, init
  File "/Users/kiennguyen/anaconda3/lib/python3.6/site-packages/colorama/__init__.py", line 2, in <module>
    from .initialise import init, deinit, reinit, colorama_text
  File "/Users/kiennguyen/anaconda3/lib/python3.6/site-packages/colorama/initialise.py", line 6, in <module>
    from .ansitowin32 import AnsiToWin32
  File "/Users/kiennguyen/anaconda3/lib/python3.6/site-packages/colorama/ansitowin32.py", line 7, in <module>
    from .winterm import WinTerm, WinColor, WinStyle
  File "/Users/kiennguyen/anaconda3/lib/python3.6/site-packages/colorama/winterm.py", line 2, in <module>
    from . import win32
  File "/Users/kiennguyen/anaconda3/lib/python3.6/site-packages/colorama/win32.py", line 8, in <module>
    import ctypes
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 555, in <module>
    _reset_cache()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 279, in _reset_cache
    CFUNCTYPE(c_int)(lambda: None)`

**Comment by cjrh** [comment]
Reformatting to make it easier to read the traceback:

```
Error detected while processing function jedi#init_python[4]..<SNR>41_init_python[27]..jedi#setup_python_imports: line 25: 

Traceback (most recent call last): 
    
    File "<string>", line 1, in <module> 
    File "<string>", line 8, in <module> 
    File "/Users/kiennguyen/.vim/bundle/jedi-vim/pythonx/jedi_vim_debug.py", line 5, in <module> from jedi_vim import PythonToVimStr 
    File "/Users/kiennguyen/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 112, in <module> import jedi 
    File "/Users/kiennguyen/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py", line 41, in <module> from jedi.api import Script, Interpreter, set_debug_function, \ 
    File "/Users/kiennguyen/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 21, in <module> from jedi import debug 
    File "/Users/kiennguyen/.vim/bundle/jedi-vim/pythonx/jedi/jedi/debug.py", line 23, in <module> from colorama import Fore, init 
    File "/Users/kiennguyen/anaconda3/lib/python3.6/site-packages/colorama/__init__.py", line 2, in <module> from .initialise import init, deinit, reinit, colorama_text 
    File "/Users/kiennguyen/anaconda3/lib/python3.6/site-packages/colorama/initialise.py", line 6, in <module> from .ansitowin32 import AnsiToWin32 
    File "/Users/kiennguyen/anaconda3/lib/python3.6/site-packages/colorama/ansitowin32.py", line 7, in <module> from .winterm import WinTerm, WinColor, WinStyle 
    File "/Users/kiennguyen/anaconda3/lib/python3.6/site-packages/colorama/winterm.py", line 2, in <module> from . import win32 
    File "/Users/kiennguyen/anaconda3/lib/python3.6/site-packages/colorama/win32.py", line 8, in <module> import ctypes 
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 555, in <module> _reset_cache() 
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 279, in _reset_cache CFUNCTYPE(c_int)(lambda: None)
```

**Comment by cjrh** [comment]
@kiennt23 if you uninstall only vim-conda, does the error in jedi-vim disappear? and if so, does the error reappear if you install only vim-conda?  I want to be sure that the problem is definitely related to vim-conda. I don't use it any more, but when I did, I definitely used jedi-vim at the same time as vim-conda, and I don't recall any problems with that.

**Comment by kiennt23** [comment]
> @kiennt23 if you uninstall only vim-conda, does the error in jedi-vim disappear? and if so, does the error reappear if you reinstall only vim-conda? I want to be sure that the problem is definitely related to vim-conda. I don't use it any more, but when I did, I definitely used jedi-vim at the same time as vim-conda, and I don't recall any problems with that.

Yes, that was exactly what I did.
