### ISSUE TITLE
Showing name Error. I have installed spacevim and anaconda as well, but I don't know why this error is showing.

### ISSUE THREAD

**Issue by lkit57a03** [cjrh/vim-conda#29]
Error detected while processing /home/harsh/.cache/vimfiles/.cache/vimrc/.dein/plugin/vim-conda.vim:
line   42:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/harsh/.cache/vimfiles/.cache/vimrc/.dein/plugin/vimconda.py", line 15, in <module>
    from subprocess import check_output, PIPE
  File "/home/harsh/anaconda3/lib/python3.7/subprocess.py", line 139, in <module>
    import _posixsubprocess
ImportError: /home/harsh/anaconda3/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Py_write_norais
Error detected while processing function <SNR>150_SetCondaPlainPath:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'vimconda' is not defined
line    2:
E121: Undefined variable: l:temppath
E15: Invalid expression: l:temppath
Error detected while processing /home/harsh/.cache/vimfiles/.cache/vimrc/.dein/plugin/vim-conda.vim:
line  124:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'vimconda' is not defined

**Comment by lkit57a03** [comment]
Also while running CondaChangeEnv, the same error is showing:
Error detected while processing function <SNR>150_CondaChangeEnv:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'vimconda' is not defined
Press ENTER or type command to continue

**Comment by SelahattinZorba** [comment]
did you solve it? i have the same problem
