### ISSUE TITLE
Source conda.sh on startup?

### ISSUE THREAD

**Issue by rddunphy** [cjrh/vim-conda#36]
First of all, thanks for creating this plugin! 

When I run vim from a terminal, everything works as it should. However, when I open vim directly through my window manager (with a key binding to `konsole -e vim`), I get the following error if I run `:CondaChangeEnv`:

```
Error detected while processing function <SNR>37_CondaChangeEnv:
line    2:
Traceback (most recent call last):
  File "/home/david/.vim/plugged/vim-conda/plugin/vimconda.py", line 54, in func
    v = self.cache[key]
KeyError: (('$CONDA_EXE info --json',), ())
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/david/.vim/plugged/vim-conda/plugin/vimconda.py", line 319, in conda_change_env
    envs = get_envs()
  File "/home/david/.vim/plugged/vim-conda/plugin/vimconda.py", line 161, in get_envs
    return get_conda_info_dict()['envs']
  File "/home/david/.vim/plugged/vim-conda/plugin/vimconda.py", line 211, in get_conda_info_dict
    output = vim_conda_runshell('$CONDA_EXE info --json')
  File "/home/david/.vim/plugged/vim-conda/plugin/vimconda.py", line 58, in func
    v = self.cache[key] = f(*args, **kwargs), time.time()
  File "/home/david/.vim/plugged/vim-conda/plugin/vimconda.py", line 148, in vim_conda_runshell
    return check_output(cmd, shell=True, executable=os.getenv('SHELL'), stdin=PIPE, stderr=PIPE).decode('utf-8')
  File "/home/david/anaconda3/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/david/anaconda3/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '$CONDA_EXE info --json' returned non-zero exit status 1.
```

After experimenting a bit, I think the issue is that `~/anaconda3/etc/profile.d/conda.sh` isn't being sourced - when I run `:! conda activate`, I get `CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.`, but if I source `conda.sh` first, it works. (However, as vim starts a new shell for each command, I still can't run `:CondaChangeEnv`, so it's possible there's something else that I'm missing.)

My question is, how can I configure vim to always source the shell script on startup? (I tried googling this and checking the help pages, but didn't have much luck.) Also, would it be possible to add a check for this, to make the error message a bit less cryptic? Thanks for your help!

**Comment by xywei** [comment]
Try setting `CONDA_EXE` to your `conda` executable in the key binding:
```
CONDA_EXE=<conda-executable> konsole -e vim
```
(You may run `echo $CONDA_EXE` in a usual terminal to get the value of `<conda-executable>`).

**Comment by rddunphy** [comment]
That fixed it, thanks for your help!
