### ISSUE TITLE
Neovim support?

### ISSUE THREAD

**Issue by harrymvr** [cjrh/vim-conda#7]
Hi,

when installing the plugin in neovim, i am getting the following error message

```
Error detected while processing function <SNR>25_SetCondaPlainPath..provider#python#Call:
line   18:
NameError("name 'vim' is not defined",)
Traceback (most recent call last):
  File "/Users/cmav/miniconda2/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 177, in handler
    rv = self._request_cb(name, args)
  File "/Users/cmav/miniconda2/lib/python2.7/site-packages/neovim/api/common.py", line 237, in filter_request_cb
    walk(self._in, args, self, name, 'request'))
  File "/Users/cmav/miniconda2/lib/python2.7/site-packages/neovim/plugin/host.py", line 65, in _on_request
    rv = handler(*args)
  File "/usr/local/Cellar/neovim/0.1.0/share/nvim/runtime/autoload/provider/script_host.py", line 76, in python_execut
e
    exec(script, self.module.__dict__)
  File "<string>", line 32, in <module>
NameError: name 'vim' is not defined
Error detected while processing function <SNR>25_SetCondaPlainPath:
line   35:
E121: Undefined variable: l:temppath
E15: Invalid expression: l:temppath
```

and then neovim segfaults. Any idea on how to fix this?

**Comment by cjrh** [comment]
Hi @harrymvr!

The PR by @russtoku should fix the problem.  I've known about the problem for a while (c.f. #6) but only got around to it now.  I also switch between vim and neovim so vim-conda should work on both.

**Comment by harrymvr** [comment]
Thanks a lot :+1:

**Comment by cjrh** [comment]
I'm closing this issue in deference to #6. We can watch it there,
